### ISSUE TITLE
muhdaizwan@earth

### ISSUE THREAD

**Issue by muhdaizwan** [MicrosoftDocs/PowerShell-Docs#11602]
### Type of issue

Outdated article

### Feedback

Support sistem  workspace
{?}  ]R[™ c 

### Page URL

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.4

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md

### Author

@muhdaizwanodzir

### Document Id

42772fd1-35e3-2672-05b1-3e5cd9c31ecf
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11598
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11600
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11589
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11599
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11597
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11601
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11594
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11580
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/11596
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11590
- [ ] https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11592
```

```[tasklist]
### Tasks
```
