### ISSUE TITLE
Rollup issue for tracking cleanup efforts

### ISSUE THREAD

**Issue by sdwheeler** [MicrosoftDocs/PowerShell-Docs#2271]
There is a lot of cleanup that needs to be done in the PowerShell Docs repo. This issue is used to itemize the cleanup tasks and link any related issues. Tasks and links to other issues can be added by editing this initial description.

* [x] Change prompts in examples per [Style Guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/FORMATTING-CODE.md)
* [x] Fill placeholder text
    - "{{ Fill in description here }}" (as well as for other fields like synopsis, just search for `{{`)
* [x] Verify/update YAML blocks for parameter properties (e.g. pipeline input, wildcard support, etc.)
    - Position numbering is wrong
    - Sometimes property values are shifted up/down by 1
* [x] Remove references to "Windows" unless talking about Windows-specific features or examples
* [ ] Retire or update outdated content or code samples
* [x] Markdown cleanup in preparation for MarkDig in June
* [ ] Cleanup formatting to match Style Guidance
   - [PowerShell-Docs Contributor Guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/CONTRIBUTING.md)
   - [MS Style Guide - Capitalization](https://docs.microsoft.com/en-us/style-guide/capitalization)
   - #1038 - Question about external links - See [MS Style Guide - URLs](https://docs.microsoft.com/en-us/style-guide/urls-web-addresses)
   - #1025 - Remove extraneous linebreaks
* [x] Cleanup folder structure to better match TOC
   - requires file redirection
* [ ] Conceptual versioning
  - separate version-specific conceptual topics into separate version TOCs

**Comment by sdwheeler** [comment]
Most of the tasks have been completed. The remaining items will need to be done on an individual article basis. Separate issues should be created for specific articles.
