### ISSUE TITLE
A hilariously meta bug on the WQL / "Using the Escape Character" page.

### ISSUE THREAD

**Issue by jones948** [MicrosoftDocs/PowerShell-Docs#8623]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell I am using.

### Version

5.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wql?view=powershell-5.1#using-the-escape-character

### Description of the documentation error

The first sentence of that this section is:

WQL uses the backslash () as its escape character. This is different from Windows PowerShell, which uses the backtick character (`).

The example backslash character between the parenthesis is missing.

### Suggested fix

You might need to escape the character in the GitHub source : )
